available_recipes = [
    {'name': 'Salatka z kurczakiem', 'calories': 400, 'macros': {'protein': 30, 'carbs': 20, 'fats': 15},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Zupa jarzynowa', 'calories': 150, 'macros': {'protein': 5, 'carbs': 25, 'fats': 5},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Omlet warzywny', 'calories': 250, 'macros': {'protein': 18, 'carbs': 10, 'fats': 15},
     'meal_type': ['breakfast']},
    {'name': 'Ryż z warzywami i tofu', 'calories': 320, 'macros': {'protein': 15, 'carbs': 50, 'fats': 8},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Kanapka z awokado i jajkiem', 'calories': 350, 'macros': {'protein': 12, 'carbs': 30, 'fats': 20},
     'meal_type': ['breakfast', 'lunch']},
    {'name': 'Kurczak z kaszą bulgur', 'calories': 450, 'macros': {'protein': 35, 'carbs': 45, 'fats': 10},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Pasta z soczewicą', 'calories': 400, 'macros': {'protein': 20, 'carbs': 60, 'fats': 8},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Łosoś z batatami', 'calories': 500, 'macros': {'protein': 35, 'carbs': 40, 'fats': 20},
     'meal_type': ['dinner']},
    {'name': 'Sałatka grecka', 'calories': 220, 'macros': {'protein': 8, 'carbs': 10, 'fats': 15},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Smoothie bananowo-szpinakowe', 'calories': 180, 'macros': {'protein': 5, 'carbs': 35, 'fats': 2},
     'meal_type': ['breakfast', 'snack']},
    {'name': 'Indyk z ryżem i brokułami', 'calories': 450, 'macros': {'protein': 40, 'carbs': 50, 'fats': 8},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Pieczone warzywa z komosą ryżową', 'calories': 300, 'macros': {'protein': 10, 'carbs': 45, 'fats': 8},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Placuszki owsiane', 'calories': 290, 'macros': {'protein': 10, 'carbs': 40, 'fats': 10},
     'meal_type': ['breakfast']},
    {'name': 'Tortilla z hummusem i warzywami', 'calories': 350, 'macros': {'protein': 10, 'carbs': 50, 'fats': 12},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Zapiekanka z batatem i kurczakiem', 'calories': 480, 'macros': {'protein': 30, 'carbs': 55, 'fats': 15},
     'meal_type': ['dinner']},
    {'name': 'Makaron z warzywami i tofu', 'calories': 400, 'macros': {'protein': 15, 'carbs': 65, 'fats': 8},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Gulasz warzywny z ciecierzycą', 'calories': 370, 'macros': {'protein': 20, 'carbs': 45, 'fats': 12},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Kanapka z masłem orzechowym', 'calories': 280, 'macros': {'protein': 8, 'carbs': 25, 'fats': 18},
     'meal_type': ['breakfast', 'snack']},
    {'name': 'Budyń chia z owocami', 'calories': 200, 'macros': {'protein': 5, 'carbs': 30, 'fats': 8},
     'meal_type': ['breakfast', 'snack']},
    {'name': 'Ryż z fasolą i warzywami', 'calories': 350, 'macros': {'protein': 12, 'carbs': 60, 'fats': 6},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Kanapka z szynką i warzywami', 'calories': 300, 'macros': {'protein': 15, 'carbs': 35, 'fats': 10},
     'meal_type': ['breakfast', 'lunch']},
    {'name': 'Sałatka z tuńczykiem', 'calories': 250, 'macros': {'protein': 20, 'carbs': 10, 'fats': 15},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Owsianka z owocami', 'calories': 320, 'macros': {'protein': 10, 'carbs': 50, 'fats': 8},
     'meal_type': ['breakfast']},
    {'name': 'Kurczak z warzywami', 'calories': 380, 'macros': {'protein': 30, 'carbs': 20, 'fats': 15},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Zupa krem z dyni', 'calories': 180, 'macros': {'protein': 4, 'carbs': 25, 'fats': 8},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Makaron pełnoziarnisty z sosem pomidorowym', 'calories': 330,
     'macros': {'protein': 10, 'carbs': 60, 'fats': 6}, 'meal_type': ['lunch', 'dinner']},
    {'name': 'Filet z dorsza z warzywami', 'calories': 300, 'macros': {'protein': 25, 'carbs': 20, 'fats': 10},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Omlet ze szpinakiem', 'calories': 270, 'macros': {'protein': 20, 'carbs': 10, 'fats': 15},
     'meal_type': ['breakfast']},
    {'name': 'Curry z ciecierzycą', 'calories': 380, 'macros': {'protein': 15, 'carbs': 50, 'fats': 15},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Batony energetyczne owsiane', 'calories': 200, 'macros': {'protein': 5, 'carbs': 30, 'fats': 8},
     'meal_type': ['snack']},
    {'name': 'Zapiekanka makaronowa z serem', 'calories': 450, 'macros': {'protein': 20, 'carbs': 60, 'fats': 15},
     'meal_type': ['dinner']},
    {'name': 'Kasza jaglana z pieczonymi warzywami', 'calories': 340, 'macros': {'protein': 12, 'carbs': 55, 'fats': 6},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Smoothie truskawkowo-jogurtowe', 'calories': 220, 'macros': {'protein': 8, 'carbs': 40, 'fats': 5},
     'meal_type': ['breakfast', 'snack']},
    {'name': 'Chili z fasolą i warzywami', 'calories': 400, 'macros': {'protein': 18, 'carbs': 50, 'fats': 12},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Tosty z jajkiem i szpinakiem', 'calories': 310, 'macros': {'protein': 15, 'carbs': 35, 'fats': 12},
     'meal_type': ['breakfast', 'lunch']},
    {'name': 'Ryż z pieczarkami i brokułami', 'calories': 330, 'macros': {'protein': 10, 'carbs': 50, 'fats': 8},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Zapiekanka z ziemniakami i szpinakiem', 'calories': 380,
     'macros': {'protein': 15, 'carbs': 45, 'fats': 10},
     'meal_type': ['dinner']},
    {'name': 'Owsianka z masłem orzechowym i bananem', 'calories': 350,
     'macros': {'protein': 12, 'carbs': 55, 'fats': 12},
     'meal_type': ['breakfast']},
    {'name': 'Quinoa z pieczoną papryką i cukinią', 'calories': 300, 'macros': {'protein': 10, 'carbs': 40, 'fats': 8},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Kanapka z hummusem i pomidorem', 'calories': 280, 'macros': {'protein': 7, 'carbs': 35, 'fats': 10},
     'meal_type': ['breakfast', 'lunch']},
    {'name': 'Koktajl białkowy z owocami leśnymi', 'calories': 250, 'macros': {'protein': 20, 'carbs': 35, 'fats': 5},
     'meal_type': ['breakfast', 'snack']},
    {'name': 'Filet z kurczaka w sosie szpinakowym', 'calories': 400,
     'macros': {'protein': 30, 'carbs': 15, 'fats': 18},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Makaron z pomidorami i bazylią', 'calories': 350, 'macros': {'protein': 12, 'carbs': 55, 'fats': 10},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Budyń jaglany z owocami', 'calories': 240, 'macros': {'protein': 6, 'carbs': 35, 'fats': 8},
     'meal_type': ['breakfast', 'snack']},
    {'name': 'Szaszłyki warzywne z tofu', 'calories': 300, 'macros': {'protein': 15, 'carbs': 30, 'fats': 12},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Jajka sadzone z pomidorami i rukolą', 'calories': 250, 'macros': {'protein': 14, 'carbs': 5, 'fats': 18},
     'meal_type': ['breakfast']},
    {'name': 'Placuszki z cukinii', 'calories': 280, 'macros': {'protein': 10, 'carbs': 30, 'fats': 12},
     'meal_type': ['breakfast', 'lunch']},
    {'name': 'Kurczak curry z warzywami', 'calories': 380, 'macros': {'protein': 30, 'carbs': 25, 'fats': 15},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Owsianka z cynamonem i orzechami', 'calories': 320, 'macros': {'protein': 10, 'carbs': 40, 'fats': 10},
     'meal_type': ['breakfast']},
    {'name': 'Pieczone bataty z fasolą i kukurydzą', 'calories': 350, 'macros': {'protein': 12, 'carbs': 60, 'fats': 8},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Makaron z cukinią i suszonymi pomidorami', 'calories': 400,
     'macros': {'protein': 15, 'carbs': 65, 'fats': 8},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Shake proteinowy z masłem orzechowym i bananem', 'calories': 300,
     'macros': {'protein': 25, 'carbs': 30, 'fats': 10}, 'meal_type': ['breakfast', 'snack', 'dinner']},
    {'name': 'Podwójna sałatka z kurczakiem', 'calories': 800, 'macros': {'protein': 60, 'carbs': 40, 'fats': 30},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Podwójna zupa jarzynowa', 'calories': 300, 'macros': {'protein': 10, 'carbs': 50, 'fats': 10},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Podwójny omlet warzywny', 'calories': 500, 'macros': {'protein': 36, 'carbs': 20, 'fats': 30},
     'meal_type': ['breakfast']},
    {'name': 'Podwójna porcja ryżu z warzywami i tofu', 'calories': 640,
     'macros': {'protein': 30, 'carbs': 100, 'fats': 16},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Podwójna kanapka z awokado i jajkiem', 'calories': 700,
     'macros': {'protein': 24, 'carbs': 60, 'fats': 40},
     'meal_type': ['breakfast', 'lunch']},
    {'name': 'Podwójny kurczak z kaszą bulgur', 'calories': 900, 'macros': {'protein': 70, 'carbs': 90, 'fats': 20},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Podwójna porcja pasty z soczewicą', 'calories': 800, 'macros': {'protein': 40, 'carbs': 120, 'fats': 16},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Podwójny łosoś z batatami', 'calories': 1000, 'macros': {'protein': 70, 'carbs': 80, 'fats': 40},
     'meal_type': ['dinner']},
    {'name': 'Podwójna sałatka grecka', 'calories': 440, 'macros': {'protein': 16, 'carbs': 20, 'fats': 30},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Podwójne smoothie bananowo-szpinakowe', 'calories': 360,
     'macros': {'protein': 10, 'carbs': 70, 'fats': 4},
     'meal_type': ['breakfast', 'snack']},
    {'name': 'Podwójny indyk z ryżem i brokułami', 'calories': 900, 'macros': {'protein': 80, 'carbs': 100, 'fats': 16},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Podwójna porcja pieczonych warzyw z komosą ryżową', 'calories': 600,
     'macros': {'protein': 20, 'carbs': 90, 'fats': 16},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Podwójne placuszki owsiane', 'calories': 580, 'macros': {'protein': 20, 'carbs': 80, 'fats': 20},
     'meal_type': ['breakfast']},
    {'name': 'Podwójna tortilla z hummusem i warzywami', 'calories': 700,
     'macros': {'protein': 20, 'carbs': 100, 'fats': 24},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Podwójna zapiekanka z batatem i kurczakiem', 'calories': 960,
     'macros': {'protein': 60, 'carbs': 110, 'fats': 30},
     'meal_type': ['dinner']},
    {'name': 'Podwójna porcja makaronu z warzywami i tofu', 'calories': 800,
     'macros': {'protein': 30, 'carbs': 130, 'fats': 16},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Podwójna porcja gulaszu warzywnego z ciecierzycą', 'calories': 740,
     'macros': {'protein': 40, 'carbs': 90, 'fats': 24},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Podwójna kanapka z masłem orzechowym', 'calories': 560,
     'macros': {'protein': 16, 'carbs': 50, 'fats': 36},
     'meal_type': ['breakfast', 'snack']},
    {'name': 'Podwójna porcja budyniu chia z owocami', 'calories': 400,
     'macros': {'protein': 10, 'carbs': 60, 'fats': 16},
     'meal_type': ['breakfast', 'snack']},
    {'name': 'Podwójna porcja ryżu z fasolą i warzywami', 'calories': 700,
     'macros': {'protein': 24, 'carbs': 120, 'fats': 12},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Podwójna kanapka z szynką i warzywami', 'calories': 600,
     'macros': {'protein': 30, 'carbs': 70, 'fats': 20},
     'meal_type': ['breakfast', 'lunch']},
    {'name': 'Podwójna sałatka z tuńczykiem', 'calories': 500, 'macros': {'protein': 40, 'carbs': 20, 'fats': 30},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Podwójna owsianka z owocami', 'calories': 640, 'macros': {'protein': 20, 'carbs': 100, 'fats': 16},
     'meal_type': ['breakfast']},
    {'name': 'Podwójna porcja kurczaka z warzywami', 'calories': 760,
     'macros': {'protein': 60, 'carbs': 40, 'fats': 30},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Podwójna zupa krem z dyni', 'calories': 360, 'macros': {'protein': 8, 'carbs': 50, 'fats': 16},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Podwójny makaron pełnoziarnisty z sosem pomidorowym', 'calories': 660,
     'macros': {'protein': 20, 'carbs': 120, 'fats': 12}, 'meal_type': ['lunch', 'dinner']},
    {'name': 'Podwójny filet z dorsza z warzywami', 'calories': 600, 'macros': {'protein': 50, 'carbs': 40, 'fats': 20},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Podwójny omlet ze szpinakiem', 'calories': 540, 'macros': {'protein': 40, 'carbs': 20, 'fats': 30},
     'meal_type': ['breakfast']},
    {'name': 'Podwójne curry z ciecierzycą', 'calories': 760, 'macros': {'protein': 30, 'carbs': 100, 'fats': 30},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Podwójne batony energetyczne owsiane', 'calories': 400,
     'macros': {'protein': 10, 'carbs': 60, 'fats': 16},
     'meal_type': ['snack']},
    {'name': 'Podwójna zapiekanka makaronowa z serem', 'calories': 900,
     'macros': {'protein': 40, 'carbs': 120, 'fats': 30},
     'meal_type': ['dinner']},
    {'name': 'Podwójna kasza jaglana z pieczonymi warzywami', 'calories': 680,
     'macros': {'protein': 24, 'carbs': 110, 'fats': 12},
     'meal_type': ['lunch', 'dinner']},
    {'name': 'Podwójne smoothie truskawkowo-jogurtowe', 'calories': 440,
     'macros': {'protein': 16, 'carbs': 80, 'fats': 10},
     'meal_type': ['breakfast', 'snack']},
    {'name': 'Podwójny shake proteinowy z masłem orzechowym i bananem', 'calories': 600,
     'macros': {'protein': 50, 'carbs': 60, 'fats': 20},
     'meal_type': ['breakfast', 'snack', 'dinner']},

    {'name': 'Tofu stir-fry z warzywami', 'calories': 300, 'macros': {'protein': 15, 'carbs': 40, 'fats': 10}, 'meal_type': ['lunch', 'dinner']},
    {'name': 'Podwójne tofu stir-fry z warzywami', 'calories': 600, 'macros': {'protein': 30, 'carbs': 80, 'fats': 20}, 'meal_type': ['lunch', 'dinner']},

    {'name': 'Pasta z pesto i pomidorkami', 'calories': 350, 'macros': {'protein': 10, 'carbs': 60, 'fats': 12}, 'meal_type': ['lunch', 'dinner']},
    {'name': 'Podwójna pasta z pesto i pomidorkami', 'calories': 700, 'macros': {'protein': 20, 'carbs': 120, 'fats': 24}, 'meal_type': ['lunch', 'dinner']},

    {'name': 'Ryż z krewetkami i brokułami', 'calories': 400, 'macros': {'protein': 25, 'carbs': 50, 'fats': 12}, 'meal_type': ['lunch', 'dinner']},
    {'name': 'Podwójna porcja ryżu z krewetkami i brokułami', 'calories': 800, 'macros': {'protein': 50, 'carbs': 100, 'fats': 24}, 'meal_type': ['lunch', 'dinner']},

    {'name': 'Frittata z warzywami', 'calories': 250, 'macros': {'protein': 18, 'carbs': 15, 'fats': 12}, 'meal_type': ['breakfast']},
    {'name': 'Podwójna frittata z warzywami', 'calories': 500, 'macros': {'protein': 36, 'carbs': 30, 'fats': 24}, 'meal_type': ['breakfast']},

    {'name': 'Chili con carne', 'calories': 450, 'macros': {'protein': 30, 'carbs': 55, 'fats': 15}, 'meal_type': ['lunch', 'dinner']},
    {'name': 'Podwójne chili con carne', 'calories': 900, 'macros': {'protein': 60, 'carbs': 110, 'fats': 30}, 'meal_type': ['lunch', 'dinner']},

    {'name': 'Smoothie z mango i jogurtem', 'calories': 200, 'macros': {'protein': 8, 'carbs': 35, 'fats': 4}, 'meal_type': ['breakfast', 'snack']},
    {'name': 'Podwójne smoothie z mango i jogurtem', 'calories': 400, 'macros': {'protein': 16, 'carbs': 70, 'fats': 8}, 'meal_type': ['breakfast', 'snack']},

    {'name': 'Kurczak tikka masala z ryżem', 'calories': 500, 'macros': {'protein': 35, 'carbs': 50, 'fats': 20}, 'meal_type': ['lunch', 'dinner']},
    {'name': 'Podwójna porcja kurczaka tikka masala z ryżem', 'calories': 1000, 'macros': {'protein': 70, 'carbs': 100, 'fats': 40}, 'meal_type': ['lunch', 'dinner']},

    {'name': 'Wrap z warzywami i hummusem', 'calories': 350, 'macros': {'protein': 12, 'carbs': 50, 'fats': 10}, 'meal_type': ['lunch', 'snack']},
    {'name': 'Podwójny wrap z warzywami i hummusem', 'calories': 700, 'macros': {'protein': 24, 'carbs': 100, 'fats': 20}, 'meal_type': ['lunch', 'snack']},

    {'name': 'Makaron z sosem pieczarkowym', 'calories': 400, 'macros': {'protein': 15, 'carbs': 60, 'fats': 10}, 'meal_type': ['lunch', 'dinner']},
    {'name': 'Podwójny makaron z sosem pieczarkowym', 'calories': 800, 'macros': {'protein': 30, 'carbs': 120, 'fats': 20}, 'meal_type': ['lunch', 'dinner']},

    {'name': 'Sałatka owocowa', 'calories': 150, 'macros': {'protein': 3, 'carbs': 35, 'fats': 2}, 'meal_type': ['snack']},
    {'name': 'Podwójna sałatka owocowa', 'calories': 300, 'macros': {'protein': 6, 'carbs': 70, 'fats': 4}, 'meal_type': ['snack']},

    {'name': 'Quinoa z pieczonym kurczakiem i brokułami', 'calories': 450, 'macros': {'protein': 30, 'carbs': 50, 'fats': 15}, 'meal_type': ['lunch', 'dinner']},
    {'name': 'Podwójna porcja quinoa z pieczonym kurczakiem i brokułami', 'calories': 900, 'macros': {'protein': 60, 'carbs': 100, 'fats': 30}, 'meal_type': ['lunch', 'dinner']},

    {'name': 'Miso ramen z tofu', 'calories': 350, 'macros': {'protein': 12, 'carbs': 55, 'fats': 10}, 'meal_type': ['lunch', 'dinner']},
    {'name': 'Podwójna porcja miso ramen z tofu', 'calories': 700, 'macros': {'protein': 24, 'carbs': 110, 'fats': 20}, 'meal_type': ['lunch', 'dinner']},

    {'name': 'Owsianka z owocami i orzechami', 'calories': 300, 'macros': {'protein': 10, 'carbs': 50, 'fats': 10}, 'meal_type': ['breakfast']},
    {'name': 'Podwójna porcja owsianki z owocami i orzechami', 'calories': 600, 'macros': {'protein': 20, 'carbs': 100, 'fats': 20}, 'meal_type': ['breakfast']},

    {'name': 'Grillowana pierś z kurczaka z batatami', 'calories': 450, 'macros': {'protein': 35, 'carbs': 40, 'fats': 15}, 'meal_type': ['lunch', 'dinner']},
    {'name': 'Podwójna porcja grillowanej piersi z kurczaka z batatami', 'calories': 900, 'macros': {'protein': 70, 'carbs': 80, 'fats': 30}, 'meal_type': ['lunch', 'dinner']},

    {'name': 'Koktajl proteinowy z bananem', 'calories': 200, 'macros': {'protein': 20, 'carbs': 30, 'fats': 2}, 'meal_type': ['snack', 'breakfast']},
    {'name': 'Podwójna porcja koktajlu proteinowego z bananem', 'calories': 400, 'macros': {'protein': 40, 'carbs': 60, 'fats': 4}, 'meal_type': ['snack', 'breakfast']},

    {'name': 'Makaron pełnoziarnisty z sosem bolońskim', 'calories': 500, 'macros': {'protein': 25, 'carbs': 65, 'fats': 15}, 'meal_type': ['lunch', 'dinner']},
    {'name': 'Podwójny makaron pełnoziarnisty z sosem bolońskim', 'calories': 1000, 'macros': {'protein': 50, 'carbs': 130, 'fats': 30}, 'meal_type': ['lunch', 'dinner']},

    {'name': 'Sałatka grecka', 'calories': 250, 'macros': {'protein': 7, 'carbs': 20, 'fats': 15}, 'meal_type': ['lunch', 'snack']},
    {'name': 'Podwójna porcja sałatki greckiej', 'calories': 500, 'macros': {'protein': 14, 'carbs': 40, 'fats': 30}, 'meal_type': ['lunch', 'snack']},

    {'name': 'Łosoś pieczony z kaszą bulgur', 'calories': 550, 'macros': {'protein': 35, 'carbs': 45, 'fats': 20}, 'meal_type': ['lunch', 'dinner']},
    {'name': 'Podwójna porcja łososia pieczonego z kaszą bulgur', 'calories': 1100, 'macros': {'protein': 70, 'carbs': 90, 'fats': 40}, 'meal_type': ['lunch', 'dinner']},

    {'name': 'Placuszki bananowe', 'calories': 300, 'macros': {'protein': 8, 'carbs': 45, 'fats': 10}, 'meal_type': ['breakfast', 'snack']},
    {'name': 'Podwójna porcja placuszków bananowych', 'calories': 600, 'macros': {'protein': 16, 'carbs': 90, 'fats': 20}, 'meal_type': ['breakfast', 'snack']},

    {'name': 'Ryż z ciecierzycą i warzywami', 'calories': 350, 'macros': {'protein': 12, 'carbs': 60, 'fats': 8}, 'meal_type': ['lunch', 'dinner']},
    {'name': 'Podwójna porcja ryżu z ciecierzycą i warzywami', 'calories': 700, 'macros': {'protein': 24, 'carbs': 120, 'fats': 16}, 'meal_type': ['lunch', 'dinner']},

    {'name': 'Omlet z szynką i serem', 'calories': 250, 'macros': {'protein': 20, 'carbs': 5, 'fats': 15}, 'meal_type': ['breakfast']},
    {'name': 'Podwójna porcja omleta z szynką i serem', 'calories': 500, 'macros': {'protein': 40, 'carbs': 10, 'fats': 30}, 'meal_type': ['breakfast']},

    {'name': 'Budyń chia z mlekiem kokosowym i malinami', 'calories': 200, 'macros': {'protein': 5, 'carbs': 25, 'fats': 10}, 'meal_type': ['snack']},
    {'name': 'Podwójna porcja budyniu chia z mlekiem kokosowym i malinami', 'calories': 400, 'macros': {'protein': 10, 'carbs': 50, 'fats': 20}, 'meal_type': ['snack']},

    {'name': 'Wrap z tuńczykiem i warzywami', 'calories': 350, 'macros': {'protein': 25, 'carbs': 40, 'fats': 10}, 'meal_type': ['lunch', 'snack']},
    {'name': 'Podwójny wrap z tuńczykiem i warzywami', 'calories': 700, 'macros': {'protein': 50, 'carbs': 80, 'fats': 20}, 'meal_type': ['lunch', 'snack']},

    {'name': 'Zupa krem z dyni', 'calories': 150, 'macros': {'protein': 3, 'carbs': 25, 'fats': 5}, 'meal_type': ['lunch', 'snack']},
    {'name': 'Podwójna porcja zupy krem z dyni', 'calories': 300, 'macros': {'protein': 6, 'carbs': 50, 'fats': 10}, 'meal_type': ['lunch', 'snack']},

    {'name': 'Sałatka z komosą ryżową, szpinakiem i fetą', 'calories': 250, 'macros': {'protein': 8, 'carbs': 30, 'fats': 12}, 'meal_type': ['lunch', 'snack']},
    {'name': 'Podwójna porcja sałatki z komosą ryżową, szpinakiem i fetą', 'calories': 500, 'macros': {'protein': 16, 'carbs': 60, 'fats': 24}, 'meal_type': ['lunch', 'snack']},

    {'name': 'Kanapka z jajkiem i awokado', 'calories': 300, 'macros': {'protein': 12, 'carbs': 35, 'fats': 15}, 'meal_type': ['breakfast', 'snack']},
    {'name': 'Podwójna kanapka z jajkiem i awokado', 'calories': 600, 'macros': {'protein': 24, 'carbs': 70, 'fats': 30}, 'meal_type': ['breakfast', 'snack']},

]
